config/routes.rb
Rails.application.routes.draw do
  root to: 'opinions#index'
  resources :users, only: %i[new create edit update]
  resources :opinions, only: [:index, :create, :edit, :update, :destroy] do
  	resources :comments, only: [:create]
  end
  resources :followings, only: [:create, :destroy]
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'users/:username', to: 'users#show', as: 'profile'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, length: { maximum: 200,
                                                too_long: 'maximum 200 characters allowed.' }

  belongs_to :user
  belongs_to :opinion
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy

  validates :text, presence: true, length: { minimum: 4, maximum: 300 }
  scope :order_by_most_recent, -> { includes(:author).order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  has_attached_file :photo
  has_attached_file :cover_image

  validates :username, presence: true, uniqueness: true, length: { minimum: 3, maximum: 12 }
  validates :fullname, presence: true, length: { minimum: 5, maximum: 20 }
  validates_attachment_content_type :photo, :cover_image,
                                    content_type: ['image/jpg', 'image/jpeg', 'image/png']

  has_many :opinions, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :followings, class_name: 'Following', foreign_key: 'follower_id'
  has_many :follows, through: :followings, source: :followed
  has_many :inverse_followings, class_name: 'Following', foreign_key: 'followed_id'
  has_many :followers, through: :inverse_followings, source: :follower

  def who_to_follow
    User.where.not(id: id).where.not(id: follows).order('created_at DESC')
  end

  def follows?(user)
    return false if user.id.nil?

    follows.where(username: user.username).first
  end

  def unfollow(user)
    f = followings.where(follower_id: user.id).first
    f ? f.destroy : false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(username: session[:username]) if session[:username]
  end

  def logged_in?
    !current_user.nil?
  end

  def require_user
    return if logged_in?

    flash[:alert] = 'Log in to perform this action'
    redirect_to sign_in_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.opinion_id = params[:opinion_id]
    @comment.user = current_user

    if @comment.save
      redirect_to opinions_path, notice: 'Comment was successfully created.'
    else
      redirect_to opinions_path, alert: @comment.errors.full_messages.join('. ').to_s
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  include FollowingsHelper

  def create
    @following = current_user.followings.new(followed_id: params[:user_id])
    @user = User.find_by_id!(user_params[:user_id])
    if @following.save
      flash[:notice] = "You are following #{User.find(params[:user_id]).fullname}"
    else
      flash[:alert] = 'Something went wrong ...'
    end
    redirect_to user_path(@user.username)
  end

  def destroy
    @user = User.find_by_id!(user_params[:user_id])
    follow = Following.where(followed_id: @user.id).where(follower_id: current_user.id).first
    follow&.destroy
    redirect_to user_path(@user.username), alert: "You unfollowed #{@user.fullname.upcase}"
  end
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  before_action :require_user

  def index
    @opinion = Opinion.new
    @opinions = Opinion.order_by_most_recent
    @not_follow = current_user.who_to_follow
  end

  def create
    @opinion = current_user.opinions.build(opinion_params)
    if @opinion.save
      flash[:notice] = 'Opinion was created successfully'
      redirect_to root_path
    else
      flash.now[:alert] = 'Something went wrong...'
    end
  end

  def edit
    @opinion = Opinion.find_by_id!(params[:id])
    @opinion
  end

  def update
    @opinion = Opinion.find_by_id!(params[:id])

    if @opinion.update(opinion_params)
      redirect_to opinions_path, notice: 'Your Opinion has been edited.'
    else
      redirect_to opinions_path, alert: "Can't complete this action."
    end
  end

  def destroy
    @opinion = Opinion.find_by_id!(opinion_params[:opinion_id])
    @opinion.destroy
    redirect_to root_path, alert: 'Opinion deleted'
  end

  private

  def opinion_params
    params.require(:opinion).permit(:opinion_id, :text)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(username: params[:session][:username])

    if @user
      session[:username] = @user.username
      flash[:notice] = 'successfully signed in'
      redirect_to root_path
    else
      flash.now[:alert] = 'Something went wrong...'
      render 'new'
    end
  end

  def destroy
    session[:username] = nil
    flash[:notice] = 'You have successfully logged out'
    redirect_to sign_in_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(signup_params)
    if @user.save
      session[:username] = @user.username
      flash[:notice] = 'Account is created sucessfully'
      redirect_to root_path
    else
      flash[:alert] = 'Something went wrong....'
      render new_user_path
    end
  end

  def show
    @user = User.find_by(username: params[:username])
    @opinion = Opinion.new
    @opinions = @user.opinions.order_by_most_recent
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(signup_params)
    if @user.save
      flash[:notice] = 'profile updated!'
      redirect_to root_path(current_user)
    else
      flash[:alert] = 'Something went wrong ...'
      render 'edit'
    end
  end

  private

  def signup_params
    params.require(:user).permit(:username, :fullname, :photo, :cover_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def after_login(partial)
    render partial: partial if logged_in?
  end

  def before_login(partial)
    render partial: partial unless logged_in?
  end

  def profile_pic(usr, size = '')
    if usr.photo.present?
      image_tag(usr.photo.to_s, alt: usr.username, class: "pr-2 rounded-circle profile-img #{size}")
    else
      image_tag('https://source.unsplash.com/random/60x60',
                alt: usr.username, class: 'pr-2 rounded-circle profile-img')
    end
  end

  def cover_pic(usr)
    if usr.cover_image.present?
      image_tag(usr.cover_image.to_s, alt: usr.username)
    else
      image_tag('https://source.unsplash.com/random/750x250',
                alt: usr.username)
    end
  end

  def different_path_partial
    if logged_in? && params[:action] == 'index'
      render partial: 'shared/right'
    elsif params[:action] == 'show'
      render partial: 'shared/profile'
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
  def user_params
    params.permit(:user_id, :authenticity_token, :button, :id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def show_follower(usr)
    res = ''
    if usr.followers.count.positive?
      res << 'Followed by '
      res << link_to(usr.followers.first.fullname, profile_path(usr.followers.first.username))
    else
      res << '0 follower'
    end
    res.html_safe
  end

  def follow_me(usr, partial)
    return if current_user == usr || current_user.follows.include?(usr)

    render partial: partial, locals: { res: usr }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Football Helper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;700&display=swap" rel="stylesheet">
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css"
    />
  </head>

  <body>
    
    <% if notice.present? %>
      <div class="notice">
        <p> <%= notice %> </p>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class="alert">
        <p> <%= alert %> </p>
      </div>
    <% end %>

<%= before_login('shared/main') %>
    <div class="container-fluid">
      <div class="row">
      <%= after_login('shared/navbar') %>
      <div class="col offset-2 mt-5" id="main">
        
        <div class="row">
          <div class="col-7 bg-light"> 
            <%= yield %> 
          </div>
            <%= different_path_partial %>
        </div>
      </div>
    </div>
  </div>

  </body>
</html>

app/views/opinions/_delete_post.html.erb
<%= form_with(:url => edit_opinion_path(@opinion), method: :delete) do |f| %>
    <%= f.hidden_field :user_id, value: @user.id %>
    <%= f.button :submit, class: 'text-danger rounded-circle mr-2 border d-block' do %>
        <i class="fa fa-plus-circle fa-lg" aria-hidden="true"></i>
    <% end %>
<% end %>

app/views/opinions/_form.html.erb
<%= form_for(@opinion, url: opinion_path) do |f| %>
    <%= f.text_field :text, autofocus: true, class: "form-control", placeholder: "Suggest any Football Game by tweet ..." %>
    <div class="actions">
       <%= f.submit @opinion.persisted? ? "Edit" : "Post", class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/opinions/_opinion.html.erb
<div class="d-flex mt-3 pt-3 border-top">
    <div class="pic">
    	<%= profile_pic(opinion.author, 'tweet-pic')%>
    </div>
    <div class="text ml-3">
        <h6><strong><%= link_to opinion.author.fullname, profile_path(opinion.author.username) , class: "text-body" %> </strong></h6>
            <p class="card-text"><%= opinion.text %> </p>
    </div>
</div>

  <div>
    <%= link_to edit_opinion_path(opinion) do %>
    <button type="button" class="btn btn-primary">Edit Opinion</button>
    <% end %>
  </div>

  <div>
    <%= form_for(opinion, :html => { :method => :delete, :remote => true }) do |f| %>
      <%= f.hidden_field :opinion_id, value: opinion.id %>
      <%= f.button :submit do %>
        <i class='icon-white icon-trash'></i> Delete
      <% end %>
    <% end %> 
  </div>
<h6 class="text-center mt-2"><em>All comments</em></h6>
<div class='post-comments-section'>
    <% opinion.comments.each do |comment| %>
      <div class="post-comments">
        <p>
          <b><%= comment.user.username %>:</b> <%= comment.content %>
        </p>
        <span> <%= comment.created_at.strftime("%Y/%m/%d") %> </span>
      </div>
    <% end %>

    <%= form_for(opinion.comments.new, url: opinion_comments_path(opinion)) do |form| %>
      <%= form.text_field :content, id: :comment_content, class: 'form-control mb-2', placeholder: 'Add new Comment' %>
      <%= form.submit 'Comment', class: 'btn btn-secondary' %>
    <% end %>
  </div>

app/views/opinions/edit.html.erb
<div class="">
  <h3>Edit Post</h3>
  <%= render 'form' %>
</div>

app/views/opinions/index.html.erb
<div class="row">
	<div class="col">
		<nav class="navbar navbar-expand-lg navbar-light">
  			<div class="container">
  				<%= link_to 'Tweet', '#', class: "navbar-brand active border-bottom border-primary" %>
    			<ul class="navbar-nav mr-auto">
      			  <li class="nav-item">
                  <%= link_to 'Videos', '#', class: "nav-link" %>
      			</li>
      			<li class="nav-item">
        		<%= link_to 'Photos', '#', class: "nav-link" %>
        
      			</li>
    			</ul>
  			</div>
		</nav>
</div>
</div>

<h3 class="mt-4"> Suggest Football Game </h3>

<div class="card mb-3">
    <div class="card-body">
        <%= form_for(@opinion, url: opinions_path) do |f| %>
            <%= f.text_field :text, autofocus: true, class: "form-control", placeholder: "Suggest any Football Game by tweet ..." %>
            <div class="actions">
          <%= f.submit class: "btn btn-primary float-right m-3" %>
        </div>
        <% end %>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <h5 class="card-title pb-2">Suggested Football Game</h5>
        <%= render @opinions %>
    </div>
</div>

app/views/shared/_follow.html.erb
<%= link_to follow_path(user_id: res.id), class: 'follow_me', method: :post do %>
<svg viewBox="0 0 496 496" class="sidebar-links__icon align-item-end">
    <g>
    <path d="M248,0C111.033,0,0,111.033,0,248c0.154,136.903,111.097,247.846,248,248c136.967,0,248-111.033,248-248S384.967,0,248,0z M248,480C119.87,480,16,376.13,16,248C16.146,119.93,119.93,16.146,248,16c128.13,0,232,103.87,232,232S376.13,480,248,480z"/>
    <path d="M400,240H256V96c0-4.418-3.582-8-8-8s-8,3.582-8,8v144H96c-4.418,0-8,3.582-8,8s3.582,8,8,8h144v144c0,4.418,3.582,8,8,8s8-3.582,8-8V256h144c4.418,0,8-3.582,8-8S404.418,240,400,240z"/>
    </g>
</svg>
<% end %>

app/views/shared/_follow_button.html.erb
<%= form_with(:url => followings_path) do |f| %>
    <%= f.hidden_field :user_id, value: user.id %>
    <%= f.button :submit, class: 'text-success rounded-circle mr-2 border d-block' do %>
         <i class="fa fa-plus-circle fa-lg" aria-hidden="true"></i>

    <% end %>
<% end %>

app/views/shared/_main.html.erb
<h2 class="p-4 backgroundl text-center">
	<span>
		<i class="fas fa-football text-white p-1 bg-primary fa-2x"></i>
	</span>
	Football Helper
</h2>

app/views/shared/_navbar.html.erb
<div class="col-2 px-1 bg-custom-side position-fixed" id="sticky-sidebar">
            <div class="nav flex-column flex-nowrap vh-100 overflow-auto text-white p-2">
        <div class="d-flex flex-wrap align-items-center p-2 border-bottom border-dark">
            <%= profile_pic(current_user, 'tweet-pic') %>
            <%= link_to current_user.fullname, profile_path(current_user.username), class: "text-white" %> 
        </div>

        <div class="d-flex flex-wrap justify-content-between p-2 border-bottom border-dark">
            <div class="follow text-center">
                <h5><%= current_user.follows.count %> <br><small>Following</small></h5>
            </div>
            <div class="follow text-center">
                <h5><%= current_user.followers.count %><br><small>Followers</small></h5>
            </div>
        </div>

    <div class="sidebar-links p-2 mt-2 ">
      <a href="#" class="sidebar-links__anchor pr-2">
      <svg viewBox="0 0 24 24" class="sidebar-links__icon">
        <g>
          <path
            d="M22.58 7.35L12.475 1.897c-.297-.16-.654-.16-.95 0L1.425 7.35c-.486.264-.667.87-.405 1.356.18.335.525.525.88.525.16 0 .324-.038.475-.12l.734-.396 1.59 11.25c.216 1.214 1.31 2.062 2.66 2.062h9.282c1.35 0 2.444-.848 2.662-2.088l1.588-11.225.737.398c.485.263 1.092.082 1.354-.404.263-.486.08-1.093-.404-1.355zM12 15.435c-1.795 0-3.25-1.455-3.25-3.25s1.455-3.25 3.25-3.25 3.25 1.455 3.25 3.25-1.455 3.25-3.25 3.25z"
          ></path>
        </g>
      </svg></a>
      <%= link_to "Home", root_path, class: "sidebar-links__anchor " %>
    </div>

    <div class="sidebar-links p-2 mt-2">
      <a href="#" class="sidebar-links__anchor pr-2">
      <svg viewBox="0 0 24 24" class="sidebar-links__icon">
        <g>
          <path
            d="M21 7.337h-3.93l.372-4.272c.036-.412-.27-.775-.682-.812-.417-.03-.776.27-.812.683l-.383 4.4h-6.32l.37-4.27c.037-.413-.27-.776-.68-.813-.42-.03-.777.27-.813.683l-.382 4.4H3.782c-.414 0-.75.337-.75.75s.336.75.75.75H7.61l-.55 6.327H3c-.414 0-.75.336-.75.75s.336.75.75.75h3.93l-.372 4.272c-.036.412.27.775.682.812l.066.003c.385 0 .712-.295.746-.686l.383-4.4h6.32l-.37 4.27c-.036.413.27.776.682.813l.066.003c.385 0 .712-.295.746-.686l.382-4.4h3.957c.413 0 .75-.337.75-.75s-.337-.75-.75-.75H16.39l.55-6.327H21c.414 0 .75-.336.75-.75s-.336-.75-.75-.75zm-6.115 7.826h-6.32l.55-6.326h6.32l-.55 6.326z"
          ></path>
        </g>
      </svg></a>
      <%= link_to "Discover", root_path, class: "sidebar-links__anchor" %>
    </div>

    <div class="sidebar-links p-2 mt-2 ">
      <a href="#" class="sidebar-links__anchor pr-2">
      <svg viewBox="0 0 24 24" class="sidebar-links__icon">
        <g>
          <path
            d="M12 11.816c1.355 0 2.872-.15 3.84-1.256.814-.93 1.078-2.368.806-4.392-.38-2.825-2.117-4.512-4.646-4.512S7.734 3.343 7.354 6.17c-.272 2.022-.008 3.46.806 4.39.968 1.107 2.485 1.256 3.84 1.256zM8.84 6.368c.162-1.2.787-3.212 3.16-3.212s2.998 2.013 3.16 3.212c.207 1.55.057 2.627-.45 3.205-.455.52-1.266.743-2.71.743s-2.255-.223-2.71-.743c-.507-.578-.657-1.656-.45-3.205zm11.44 12.868c-.877-3.526-4.282-5.99-8.28-5.99s-7.403 2.464-8.28 5.99c-.172.692-.028 1.4.395 1.94.408.52 1.04.82 1.733.82h12.304c.693 0 1.325-.3 1.733-.82.424-.54.567-1.247.394-1.94zm-1.576 1.016c-.126.16-.316.246-.552.246H5.848c-.235 0-.426-.085-.552-.246-.137-.174-.18-.412-.12-.654.71-2.855 3.517-4.85 6.824-4.85s6.114 1.994 6.824 4.85c.06.242.017.48-.12.654z"
          ></path>
        </g>
      </svg></a>
      <%= link_to "Profile", profile_path(current_user.username), class: "sidebar-links__anchor" %>
    </div>

   <div class="sidebar-links p-2 mt-2 ">
      <a href="#" class="sidebar-links__anchor pr-2">
    <svg class="sidebar-links__icon" viewBox="0 0 512 512" xml:space="preserve">
      <g><g>
          <path d="M255.15,468.625H63.787c-11.737,0-21.262-9.526-21.262-21.262V64.638c0-11.737,9.526-21.262,21.262-21.262H255.15
            c11.758,0,21.262-9.504,21.262-21.262S266.908,0.85,255.15,0.85H63.787C28.619,0.85,0,29.47,0,64.638v382.724
            c0,35.168,28.619,63.787,63.787,63.787H255.15c11.758,0,21.262-9.504,21.262-21.262
            C276.412,478.129,266.908,468.625,255.15,468.625z"/>
        </g></g><g><g>
          <path d="M505.664,240.861L376.388,113.286c-8.335-8.25-21.815-8.143-30.065,0.213s-8.165,21.815,0.213,30.065l92.385,91.173
            H191.362c-11.758,0-21.262,9.504-21.262,21.262c0,11.758,9.504,21.263,21.262,21.263h247.559l-92.385,91.173
            c-8.377,8.25-8.441,21.709-0.213,30.065c4.167,4.21,9.653,6.336,15.139,6.336c5.401,0,10.801-2.041,14.926-6.124l129.276-127.575
            c4.04-3.997,6.336-9.441,6.336-15.139C512,250.302,509.725,244.88,505.664,240.861z"/>
        </g></g>
      </svg>
    </a>
      <%= link_to "Sign out", logout_path, method: :delete, class: "sidebar-links__anchor" %>
  </div>
</div>
</div>

<div class="col-10 offset-2 position-fixed navbar-dark bg-custom-top" style="z-index: 3">
      <nav class="navbar navbar-expand-lg navbar-dark sticky-top">
        <div class="container">
          <%= link_to '#' do %> 
          <i class="fas fa-football text-white fa-2x"></i>
          <% end %>&nbsp;&nbsp;
          <%= link_to 'Football', '#', class: "navbar-brand" %>
          <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarMenu">
          <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarMenu">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item ml-3">
            <%= link_to '#' do %> 
          <i class="fas fa-search nav-link"></i>
          <% end %>
            </li>
            <li class="nav-item ml-3">
              <%= link_to '#' do %> 
          <i class="fas fa-envelope nav-link"></i>
          <% end %>
            </li><li class="nav-item ml-3">
              <%= link_to '#' do %> 
          <i class="fas fa-pen nav-link"></i>
          <% end %>
        
            </li>
              <li class="nav-item ml-3">
                  <%= link_to edit_user_path(current_user) do %> 
    <svg viewBox="0 0 512 512" class="sidebar-links__icon align-items-end">
    <g><g>
    <path d="M496.659,312.107l-47.061-36.8c0.597-5.675,1.109-12.309,1.109-19.328c0-7.019-0.491-13.653-1.109-19.328l47.104-36.821
        c8.747-6.912,11.136-19.179,5.568-29.397L453.331,85.76c-5.227-9.557-16.683-14.464-28.309-10.176l-55.531,22.293
        c-10.645-7.68-21.803-14.165-33.344-19.349l-8.448-58.901C326.312,8.448,316.584,0,305.086,0h-98.133
        c-11.499,0-21.205,8.448-22.571,19.456l-8.469,59.115c-11.179,5.035-22.165,11.435-33.28,19.349l-55.68-22.357
        C76.52,71.531,64.04,76.053,58.856,85.568L9.854,170.347c-5.781,9.771-3.392,22.464,5.547,29.547l47.061,36.8
        c-0.747,7.189-1.109,13.44-1.109,19.307s0.363,12.117,1.109,19.328l-47.104,36.821c-8.747,6.933-11.115,19.2-5.547,29.397
        l48.939,84.672c5.227,9.536,16.576,14.485,28.309,10.176l55.531-22.293c10.624,7.659,21.781,14.144,33.323,19.349l8.448,58.88
        C185.747,503.552,195.454,512,206.974,512h98.133c11.499,0,21.227-8.448,22.592-19.456l8.469-59.093
        c11.179-5.056,22.144-11.435,33.28-19.371l55.68,22.357c2.688,1.045,5.483,1.579,8.363,1.579c8.277,0,15.893-4.523,19.733-11.563
        l49.152-85.12C507.838,331.349,505.448,319.083,496.659,312.107z M256.019,341.333c-47.061,0-85.333-38.272-85.333-85.333
        s38.272-85.333,85.333-85.333s85.333,38.272,85.333,85.333S303.08,341.333,256.019,341.333z"/>
    </g></g></svg> 
<% end %>
            </li>
          </ul>
          </div>
        </div>
    </nav>
    </div>
  </div>

app/views/shared/_profile.html.erb
<div class="col-3 offset-7 border-left px-1 bg-light position-fixed pt-3 py-4" >
<div class="text-center mb-2">
      <% if current_user == @user %>
        <span>Edit</span>
      <% else %>
        <% if current_user != @user && current_user.follows?(@user) %>
            <%= form_with(:url => following_path(@user), method: :delete) do |f| %>
                <%= f.hidden_field :user_id, value: @user.id %>
                <%= f.button :submit, class: 'text-danger rounded-circle mr-2 border d-block' do %>
                <i class="fa fa-plus-circle fa-lg" aria-hidden="true"></i>
                <% end %>
            <% end %>
        <% else %>
          <%= form_with(:url => followings_path) do |f| %>
            <%= f.hidden_field :user_id, value: @user.id %>
            <%= f.button :submit, class: 'text-success rounded-circle mr-2 border d-block' do %>
                <i class="fa fa-plus-circle fa-lg" aria-hidden="true"></i>
            <% end %>
        <% end %>
        <% end %>
      <% end %>
      
      <%= profile_pic(@user, 'tweet-pic')%>
     
     <div class="user-info">
        <h5 class="mt-2"><%= link_to @user.fullname, profile_path(@user.username), class: "user-name-p" %> <br><small class="text-gray">@<%= @user.username %></small></h5>
        <div class="stats border-top border-bottom pt-2 d-flex flex-wrap justify-content-around">
            <h5><%= @user.opinions.count %> <br><small>Opinions</small></h5>
            <h5><%= @user.follows.count %> <br><small>Following</small></h5>
            <h5><%= @user.followers.count %><br><small>Followers</small></h5>
        </div>
     </div>
</div>

    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Followed by</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Following</a>
        </li>
        </ul>

    <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
        
        <% @user.followers.each do |follower| %>
            <div class="d-flex align-items-center mb-2 mt-2 who-to-follow justify-content-around">
                    <div class="author">
                        <%= profile_pic(follower, 'tweet-pic')%>
                    </div>
                    <div>
                        <h6><strong> <%= link_to follower.fullname, profile_path(follower.username), class: "text-dark" %></strong></h6>
                        <small class="text-gray">@<%= follower.username %></small>
                    </div>
                    <div class="ml-5">
                        
                    </div>    
            </div>
        <% end %>
    </div>
    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
        
        <% @user.follows.each do |follow| %>
            <div class="d-flex align-items-center mb-2 mt-2 who-to-follow justify-content-around">
                    <div class="author">
                        <%= profile_pic(follow, 'tweet-pic')%>
                    </div>
                    <div>
                        <h6><strong> <%= link_to follow.fullname, profile_path(follow.username), class: "text-dark" %></strong></h6>
                        <small class="text-gray">@<%= follow.username %></small>
                    </div>
                    <div class="ml-5">
                        
                    </div>
                         
                    </div>
         <% end %>

    </div>
    </div>

</div>

app/views/shared/_unfollow_button.html.erb
<%= form_with(:url => following_path(@user), method: :delete) do |f| %>
  <%= f.hidden_field :user_id, value: @user.id %>
  <%= f.button :submit, class: 'text-danger rounded-circle mr-2 border d-block' do %>
     <i class="fa fa-minus-circle fa-lg" aria-hidden="true"></i>
  <% end %>
<% end %>